### ISSUE TITLE
Observation Temperatures

### ISSUE THREAD

**Issue by SCarns** [sbender9/signalk-noaa-weather#15]
NOAA Plugin doesn't appear specify ºC when importing observed temperature and dew point, so the conversion to ºK doesn't happen in SK. The result in WilhelmSK is that the temp is -450ºF, instead of the correct result.

**Comment by sbender9** [comment]
Looks like they changed the format of their data. Fixing now...

**Comment by sbender9** [comment]
fix released in v1.3.5
